# GraphQL Placeholder API Performance Test Configuration

protocol: graphql

execution:
  threads: 5
  iterations: 10
  rampUpSeconds: 2
  holdSeconds: 5

request:
  name: "GraphQL Placeholder API - Users Query"
  endpoint: "https://graphqlzero.almansi.me/api"
  graphqlQuery: |
    query {
      users(options: { paginate: { page: 1, limit: 10 } }) {
        data {
          id
          name
          username
          email
        }
        meta {
          totalCount
        }
      }
    }

templates:
  queryPath: "templates/graphql/query/get_users.graphql"
  headersPath: "templates/graphql/headers/default_headers.json"
  responsePath:
    success: "templates/graphql/response/success_schema.json"
    error: "templates/graphql/response/error_schema.json"
