# Rick and Morty API Performance Test Configuration

protocol: graphql

execution:
  threads: 5
  iterations: 10
  rampUpSeconds: 2
  holdSeconds: 5

request:
  name: "Rick and Morty API - Characters Query"
  endpoint: "https://rickandmortyapi.com/graphql"
  graphqlQuery: |
    query {
      characters(page: 1) {
        info {
          count
          pages
        }
        results {
          id
          name
          status
          species
          type
          gender
        }
      }
    }

templates:
  queryPath: "templates/graphql/body/get_rick_and_morty_characters.graphql"
  headersPath: "templates/graphql/headers/default_headers.json"
  responsePath:
    success: "templates/graphql/response/success_schema.json"
    error: "templates/graphql/response/error_schema.json"
