# GraphQL Performance Test Configuration

protocol: graphql

execution:
  threads: 3
  iterations: 5
  rampUpSeconds: 1
  holdSeconds: 3

request:
  name: "GraphQL Countries API Test"
  endpoint: "https://countries.trevorblades.com/"
  graphqlQuery: |
    query GetCountries {
      countries {
        code
        name
        capital
        currency
      }
    }
  headers:
    Content-Type: "application/json"

templates:
  queryPath: "templates/graphql/body/get_countries.graphql"
  headersPath: "templates/graphql/headers/default_headers.json"
