# HTTP Performance Test Configuration

protocol: http

execution:
  threads: 5
  iterations: 10
  rampUpSeconds: 2
  holdSeconds: 5

request:
  name: "HTTP API Test"
  endpoint: "https://httpbin.org/post"
  method: "POST"
  body: '{"message": "Hello World"}'
  headers:
    Content-Type: "application/json"
    Accept: "application/json"

templates:
  bodyPath: "templates/http/body/create_user.json"
  headersPath: "templates/http/headers/default_headers.json"
