name: Core Module CI with Maven

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'generic-performance-framework-core/**'
      - '.github/workflows/ci.yml'
      - 'pom.xml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'generic-performance-framework-core/**'
      - '.github/workflows/ci.yml'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  build-and-test-core:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build core module
      run: mvn -B clean compile --file generic-performance-framework-core/pom.xml

    - name: Run core module tests
      run: mvn -B test --file generic-performance-framework-core/pom.xml

    - name: Generate test report for core module
      if: always()
      run: mvn surefire-report:report-only --file generic-performance-framework-core/pom.xml
      
    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: core-test-report
        path: 'generic-performance-framework-core/target/site/surefire-report.html'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Verify package integrity
      run: |
        mvn -B package --file generic-performance-framework-core/pom.xml -DskipTests
        echo "Core JAR files generated:"
        ls -la generic-performance-framework-core/target/*.jar || echo "No JAR files found"