name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run Tests
      run: mvn test
    
    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/jmeter-reports/
        retention-days: 5
    
    - name: Generate Documentation
      run: mvn site
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: target/site
        branch: gh-pages
        clean: true
    
    - name: Publish Performance Reports
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: target/jmeter-reports
        branch: gh-pages
        target-folder: reports
        clean-exclude: |
          *.html
          css/**
          js/**
          images/**
