name: Static Code Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B clean compile
    
    - name: Run SpotBugs
      run: mvn spotbugs:spotbugs -DskipTests
    
    - name: Upload SpotBugs Report
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: spotbugs-report
        path: target/spotbugsXml.xml
        retention-days: 7
    
    - name: Run Checkstyle
      run: mvn checkstyle:check -DskipTests
      continue-on-error: true  # Don't fail the workflow on style violations
    
    - name: Upload Checkstyle Report
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: checkstyle-report
        path: target/checkstyle-result.xml
        retention-days: 7
        
  code-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Run tests with Jacoco
      run: mvn -B test jacoco:report
    
    - name: Upload Coverage Report
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: target/site/jacoco/
        retention-days: 7
    
    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: target/site/jacoco/jacoco.csv
        badges-directory: .github/badges
        generate-coverage-badge: true
        generate-branches-badge: true
    
    - name: Commit and Push Badges
      if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .github/badges/jacoco.svg
        git add .github/badges/branches.svg
        git commit -m "Update code coverage badges" || echo "No changes to commit"
        git push
